version: 2

jobs:
    build:
        environment:
            CC_TEST_REPORTER_ID: dea42ba671f5846bf36d079ef486efb3256fb66d9c7278d9ff2b12b9a161ada0
        docker:
            - image: cimg/php:8.1.9
        resource_class: small
        working_directory: ~/repo
        steps:
            - checkout
            - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            - run: chmod +x ./cc-test-reporter
            - run: ./cc-test-reporter before-build
            - run: ./cc-test-reporter after-build -t clover -d -p /var/www/html/vendor/vairogs/vairogs --exit-code $?
