services:
    Vairogs\Twig\Pagination\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Php\Extension:
        public: false
        tags:
            -
                name: twig.extension
